const NODE = {
  TYPE: {
      NUMBER: "NT_NUMBER",

      PLUS: "NT_PLUS",
      MINUS: "NT_MINUS",

      ADD: "NT_ADD",
      SUB: "NT_SUB",
      MULTIPLY: "NT_MULIPLY",
      DIVIDE: "NT_DIVIDE",

      MOD: "NT_MOD",
      INT_DIVIDE: "NT_INT_DIVIDE",
      POW: "NT_POW",

      BITWISE_AND: "NT_BITWISE_AND",
      BITWISE_OR: "NT_BITWISE_OR",

      LOGNBASEX: "NT_LOG_BASE",
      NAT_LOG: "NT_NAT_LOG",
      NTH_ROOT: "NT_NTH_ROOT",

      BINARY_STRING: "NT_BINARY_STRING",
      BINARY: "NT_BINARY",

      HEXADECIMAL_STRING: "NT_HEXADECIMAL_STRING",
      HEXADECIMAL: "NT_HEXADECIMAL",

      OCTAL_STRING: "NT_OCTAL_STRING",
      OCTAL: "NT_OCTAL",
  }
};

module.exports = NODE;
